parameters:
  platform: "macOS"
  vmImage: "macOS-10.13"
  ESY__PREFIX_PATH: $(Pipeline.Workspace)/.esy
  ESY__CACHE_INSTALL_PATH: $(Pipeline.Workspace)/.esy/3____________________________________________________________________/i

jobs:
  - job: ${{ parameters.platform }}
    pool:
      vmImage: ${{ parameters.vmImage }}
      demands: node.js
    timeoutInMinutes: 120 # This is mostly for Windows
    variables:
      ESY__PREFIX: ${{ parameters.ESY__PREFIX_PATH }}

    steps:
      - template: utils/use-node.yml
      - template: utils/use-esy.yml
      - task: CacheBeta@0
        inputs:
          key: |
            esy
            $(Agent.OS)
            ${{ parameters.ESY__CACHE_INSTALL_PATH }}
            $(Build.SourcesDirectory)/esy.lock/index.json
          path: ${{ parameters.ESY__CACHE_INSTALL_PATH }}
      - script: "esy install"
        displayName: "esy install"
      - script: "esy build"
        displayName: "esy build"
      # - template: utils/create-docs.yml
      - script: "echo 'we should write tests'"
        displayName: "Test command"
      - script: "esy release"
        displayName: "esy release"
      - task: PublishPipelineArtifact@0
        displayName: "Publish Artifact: ${{ parameters.platform }}"
        inputs:
          targetPath: "_release"
          artifactName: ${{ parameters.platform }}
