// Generated by BUCKLESCRIPT VERSION 6.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Components$Test(Props) {
  return React.createElement("div", undefined, "Reuniverse");
}

var Test = /* module */[/* make */Components$Test];

exports.Test = Test;
/* react Not a pure module */
