// Generated by BUCKLESCRIPT VERSION 6.0.2, PLEASE EDIT WITH CARE
'use strict';


var Background = 0;

var Container = 0;

var Footer = 0;

var Global = 0;

var Label = 0;

var Link = 0;

var Loading = 0;

var Logo = 0;

var Nav = 0;

var Package_card = 0;

var Package_list = 0;

var Search_input = 0;

var Tiny_title = 0;

exports.Background = Background;
exports.Container = Container;
exports.Footer = Footer;
exports.Global = Global;
exports.Label = Label;
exports.Link = Link;
exports.Loading = Loading;
exports.Logo = Logo;
exports.Nav = Nav;
exports.Package_card = Package_card;
exports.Package_list = Package_list;
exports.Search_input = Search_input;
exports.Tiny_title = Tiny_title;
/* No side effect */
