// Generated by BUCKLESCRIPT VERSION 6.0.2, PLEASE EDIT WITH CARE
'use strict';


var Index = 0;

var Package = 0;

var Version = 0;

var Repository = 0;

exports.Index = Index;
exports.Package = Package;
exports.Version = Version;
exports.Repository = Repository;
/* No side effect */
