// Generated by BUCKLESCRIPT VERSION 6.0.2, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");

function $less$pipe$great(o, d) {
  if (o !== undefined) {
    return Caml_option.valFromOption(o);
  } else {
    return d;
  }
}

var $$Option = /* module */[/* <|> */$less$pipe$great];

exports.$$Option = $$Option;
/* No side effect */
