// Generated by BUCKLESCRIPT VERSION 6.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Components = require("./design_system/components.bs.js");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");

ReactDOMRe.renderToElementWithId(React.createElement(Components.Test[/* make */0], { }), "app");

/*  Not a pure module */
