// Generated by BUCKLESCRIPT VERSION 6.0.2, PLEASE EDIT WITH CARE
'use strict';


var git_commit = "%%GIT_COMMIT%%";

var build_time = "%%BUILD_TIME%%";

exports.git_commit = git_commit;
exports.build_time = build_time;
/* No side effect */
