// Generated by BUCKLESCRIPT VERSION 6.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Search = require("./search/search.bs.js");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var Design_system = require("./design_system/design_system.bs.js");

function Webapp$Main(Props) {
  var match = React.useState((function () {
          return "";
        }));
  return React.createElement(Design_system.Global[/* make */2], {
              children: null
            }, React.createElement(Design_system.Background[/* make */1], { }), React.createElement(Design_system.Nav[/* make */0], {
                  children: null
                }, React.createElement(Design_system.Logo[/* make */1], { }), React.createElement(Design_system.Search_input[/* make */1], {
                      onChange: match[1],
                      placeholder: "Search..."
                    })), React.createElement(Search.App[/* make */0], {
                  filter: match[0]
                }));
}

var Main = /* module */[/* make */Webapp$Main];

ReactDOMRe.renderToElementWithId(React.createElement(Webapp$Main, { }), "app");

exports.Main = Main;
/*  Not a pure module */
